apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srutisucharita/argocd-demos.git    # Replace it with your forked repo
    targetRevision: main
    path: declarative_approach/online_shop
  destination:
    server: https://B54354781516097483C17CA08FD75039.gr7.us-east-1.eks.amazonaws.com    # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
